export {
  canonicalize,
  sha256Hex,
  signCompactJws,
  verifyCompactJws,
  coverageEventId,
  grantIdComp,
  grantIdPaid,
  grantIdTransfer,
  humanRef,
  paymentId,
  subscriptionRef,
  ulid,
  acceptedVersions,
  negotiate,
  validateCoverageSnapshot,
  validateFeedEvent,
  grantEnvelopeHash,
  validateGrantEnvelope,
  verifyGrantSignature,
  operationChallenge,
  validateOperation,
  receiptSigningBytes,
  validateReceipt,
  verifyReceiptSignature,
  validateResultEnvelope,
  validateTokenClaims,
  verifyAccessJwt,
  parseRegistrationAttestation,
  verifyAssertion,
} from "../../../../packages/vendor-contracts/src/index.ts";
export type {
  TokenAudience,
  AccessCertsDocument,
  Assertion,
} from "../../../../packages/vendor-contracts/src/index.ts";

export const CHANNEL_VERSIONS = {
  aboClinic: 2,
  aboConsole: 2,
  backendRpc: 2,
  platformClinic: 2,
  platformFeed: 2,
  vendorEntrypoint: 2,
  platformDo: 2,
  paymobReturn: 2,
  paymobAdapter: 2,
} as const;
