-- =============================================================================
-- Service Catalog (015): pricing, eligibility, and catalog read RPCs
-- Populated in user-story phases (US1, US2, US6).
-- =============================================================================
