"""Resilience envelope: bounded queue, timeouts, retry, cancel, and model swap."""

from gateway.pipeline.cancel import (
    CancellableRunnerCall,
    abort_httpx_call,
    cancellable_stream,
    log_cancelled,
    run_cancellable,
)
from gateway.pipeline.queue import (
    GenerationQueue,
    QueueEntry,
    QueueSlot,
    ShutdownCoordinator,
    create_generation_queue,
)
from gateway.pipeline.retry import (
    RetryContext,
    execute_with_retry,
    is_retryable_error,
    select_retry_runner,
    should_retry,
)
from gateway.pipeline.swap import (
    SwapCandidate,
    emit_model_swap,
    ensure_capable_runner,
    find_ready_runner,
    find_swap_candidate,
    wait_for_runner_ready,
)
from gateway.pipeline.timeout import (
    FirstTokenTimeout,
    FirstTokenTracker,
    ModelSwapFirstTokenTimeout,
    TimeoutBreached,
    TimeoutKind,
    TimeoutSettings,
    TotalTimeout,
    await_first_token,
    first_token_timeout,
    first_token_timeout_s,
    run_with_total_timeout,
    stream_with_first_token_timeout,
    total_timeout,
)

__all__ = [
    "CancellableRunnerCall",
    "FirstTokenTimeout",
    "FirstTokenTracker",
    "GenerationQueue",
    "ModelSwapFirstTokenTimeout",
    "QueueEntry",
    "QueueSlot",
    "RetryContext",
    "ShutdownCoordinator",
    "SwapCandidate",
    "TimeoutBreached",
    "TimeoutKind",
    "TimeoutSettings",
    "TotalTimeout",
    "abort_httpx_call",
    "await_first_token",
    "cancellable_stream",
    "create_generation_queue",
    "ensure_capable_runner",
    "emit_model_swap",
    "execute_with_retry",
    "find_ready_runner",
    "find_swap_candidate",
    "first_token_timeout",
    "first_token_timeout_s",
    "is_retryable_error",
    "log_cancelled",
    "run_cancellable",
    "run_with_total_timeout",
    "select_retry_runner",
    "should_retry",
    "stream_with_first_token_timeout",
    "total_timeout",
    "wait_for_runner_ready",
]
