import type { Appointment, Doctor } from './types'

const today = new Date()
today.setHours(0, 0, 0, 0)

function timeToday(hours: number, minutes: number): string {
  const d = new Date(today)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString()
}

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'dr-hassan',
    name: 'Dr. Omar Hassan',
    specialty: 'General Practice',
    status: 'with_patient',
    currentPatientId: 'apt-003',
    currentPatientName: 'Fatima El-Sayed',
    patientsSeenToday: 6,
    idleSince: null,
  },
  {
    id: 'dr-nadia',
    name: 'Dr. Nadia Farouk',
    specialty: 'Pediatrics',
    status: 'available',
    currentPatientId: null,
    currentPatientName: null,
    patientsSeenToday: 4,
    idleSince: minutesAgo(8),
  },
  {
    id: 'dr-karim',
    name: 'Dr. Karim Mostafa',
    specialty: 'Internal Medicine',
    status: 'on_break',
    currentPatientId: null,
    currentPatientName: null,
    patientsSeenToday: 5,
    idleSince: minutesAgo(15),
  },
  {
    id: 'dr-layla',
    name: 'Dr. Layla Ibrahim',
    specialty: 'Dermatology',
    status: 'available',
    currentPatientId: null,
    currentPatientName: null,
    patientsSeenToday: 3,
    idleSince: minutesAgo(22),
  },
]

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-001',
    patientName: 'Ahmed Mahmoud',
    mrn: 'MRN-1045823',
    scheduledTime: timeToday(8, 30),
    status: 'completed',
    preferredDoctorId: 'dr-hassan',
    preferredDoctorName: 'Dr. Omar Hassan',
    appointmentType: 'follow_up',
    isWalkIn: false,
    arrivedAt: timeToday(8, 22),
    checkedInAt: timeToday(8, 25),
    consultationStartedAt: timeToday(8, 32),
    assignedDoctorId: 'dr-hassan',
    assignedDoctorName: 'Dr. Omar Hassan',
  },
  {
    id: 'apt-002',
    patientName: 'Sara Abdel-Rahman',
    mrn: 'MRN-0923417',
    scheduledTime: timeToday(9, 0),
    status: 'completed',
    preferredDoctorId: 'dr-nadia',
    preferredDoctorName: 'Dr. Nadia Farouk',
    appointmentType: 'new_patient',
    isWalkIn: false,
    arrivedAt: timeToday(8, 55),
    checkedInAt: timeToday(8, 58),
    consultationStartedAt: timeToday(9, 5),
    assignedDoctorId: 'dr-nadia',
    assignedDoctorName: 'Dr. Nadia Farouk',
  },
  {
    id: 'apt-003',
    patientName: 'Fatima El-Sayed',
    mrn: 'MRN-0876294',
    scheduledTime: timeToday(9, 30),
    status: 'in_progress',
    preferredDoctorId: 'dr-hassan',
    preferredDoctorName: 'Dr. Omar Hassan',
    appointmentType: 'consultation',
    isWalkIn: false,
    arrivedAt: timeToday(9, 18),
    checkedInAt: timeToday(9, 22),
    consultationStartedAt: minutesAgo(18),
    assignedDoctorId: 'dr-hassan',
    assignedDoctorName: 'Dr. Omar Hassan',
  },
  {
    id: 'apt-004',
    patientName: 'Youssef Kamal',
    mrn: 'MRN-1103845',
    scheduledTime: timeToday(9, 45),
    status: 'checked_in',
    preferredDoctorId: 'dr-karim',
    preferredDoctorName: 'Dr. Karim Mostafa',
    appointmentType: 'follow_up',
    isWalkIn: false,
    arrivedAt: timeToday(9, 35),
    checkedInAt: minutesAgo(32),
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    exceptions: { copayDue: true },
  },
  {
    id: 'apt-005',
    patientName: 'Mona Hesham',
    mrn: 'MRN-0765192',
    scheduledTime: timeToday(10, 0),
    status: 'checked_in',
    preferredDoctorId: 'dr-layla',
    preferredDoctorName: 'Dr. Layla Ibrahim',
    appointmentType: 'procedure',
    isWalkIn: false,
    arrivedAt: timeToday(9, 50),
    checkedInAt: minutesAgo(24),
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    exceptions: { formsIncomplete: true },
  },
  {
    id: 'apt-006',
    patientName: 'Hassan Ali',
    mrn: 'MRN-0982736',
    scheduledTime: timeToday(10, 15),
    status: 'arrived',
    preferredDoctorId: 'dr-nadia',
    preferredDoctorName: 'Dr. Nadia Farouk',
    appointmentType: 'consultation',
    isWalkIn: false,
    arrivedAt: minutesAgo(5),
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    exceptions: { selfCheckInPending: true, formsIncomplete: true },
  },
  {
    id: 'apt-007',
    patientName: 'Nour El-Din',
    mrn: 'MRN-0638471',
    scheduledTime: timeToday(10, 30),
    status: 'scheduled',
    preferredDoctorId: 'dr-hassan',
    preferredDoctorName: 'Dr. Omar Hassan',
    appointmentType: 'follow_up',
    isWalkIn: false,
    arrivedAt: null,
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
  },
  {
    id: 'apt-008',
    patientName: 'Rania Soliman',
    mrn: 'MRN-1159028',
    scheduledTime: timeToday(10, 45),
    status: 'scheduled',
    preferredDoctorId: null,
    preferredDoctorName: null,
    appointmentType: 'walk_in',
    isWalkIn: true,
    arrivedAt: null,
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    notes: 'Walk-in — general checkup',
  },
  {
    id: 'apt-009',
    patientName: 'Karim Fawzy',
    mrn: 'MRN-0814563',
    scheduledTime: timeToday(9, 15),
    status: 'no_show',
    preferredDoctorId: 'dr-karim',
    preferredDoctorName: 'Dr. Karim Mostafa',
    appointmentType: 'consultation',
    isWalkIn: false,
    arrivedAt: null,
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
  },
  {
    id: 'apt-010',
    patientName: 'Dina Mostafa',
    mrn: 'MRN-1026784',
    scheduledTime: timeToday(11, 0),
    status: 'scheduled',
    preferredDoctorId: 'dr-layla',
    preferredDoctorName: 'Dr. Layla Ibrahim',
    appointmentType: 'new_patient',
    isWalkIn: false,
    arrivedAt: null,
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    exceptions: { formsIncomplete: true, insuranceIssue: true },
  },
  {
    id: 'apt-011',
    patientName: 'Omar Tarek',
    mrn: 'MRN-0945120',
    scheduledTime: timeToday(8, 0),
    status: 'cancelled',
    preferredDoctorId: 'dr-hassan',
    preferredDoctorName: 'Dr. Omar Hassan',
    appointmentType: 'follow_up',
    isWalkIn: false,
    arrivedAt: null,
    checkedInAt: null,
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
    notes: 'Patient called to reschedule',
  },
  {
    id: 'apt-012',
    patientName: 'Laila Nasser',
    mrn: 'MRN-0789346',
    scheduledTime: timeToday(10, 0),
    status: 'checked_in',
    preferredDoctorId: 'dr-nadia',
    preferredDoctorName: 'Dr. Nadia Farouk',
    appointmentType: 'consultation',
    isWalkIn: false,
    arrivedAt: timeToday(9, 42),
    checkedInAt: minutesAgo(8),
    consultationStartedAt: null,
    assignedDoctorId: null,
    assignedDoctorName: null,
  },
]
